### ISSUE TITLE
If I want to say hello to players from the minecraft server, what should I do?

### ISSUE THREAD

**Issue by Yuan-ZW** [PHLAK/docker-minecraft#1]
I attached to the container and entered 'say hello', but there is no output.
Moreover, I cant detach from the container without stopping it.

**Comment by PHLAK** [comment]
I don't know of a way to do this currently. I tried `docker attach` with the same results as you (no output, can't detach without killing the server). If you find a way to accomplish this let us know.

**Comment by PHLAK** [comment]
I also tried `echo "say Hello world!" > /proc/1/fd/0` from within the running container without success. :disappointed:

**Comment by Yuan-ZW** [comment]
I found it!

I added `-it` when starting the container. Like this:
`docker run -itd -p 25565:25565 -v minecraft-data:/etc/minecraft --name mc phlak/minecraft`

Now I can attach with the server by `docker attach mc`, and detach by pressing Ctrl+p and Ctrl+q.

`say hello` is working now!  ٩(๑❛ᴗ❛๑)۶

![_20181205154301](https://user-images.githubusercontent.com/31435244/49498577-7706e400-f8a6-11e8-8839-95a5fd1a7221.png)

**Comment by PHLAK** [comment]
AWESOME! Thanks for finding this. I'll update the docs with this info.

**Comment by PHLAK** [comment]
Keeping this open until I update the docs.

**Comment by PHLAK** [comment]
Resolved with d9728f4
